# Generated by Django 4.1.4 on 2022-12-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental_id',
            new_name='rental',
        ),
    ]
